### ISSUE TITLE
Rstudio crashes when fitting using luz

### ISSUE THREAD

**Issue by MislavSag** [mlverse/luz#102]
I am posting the issue from torch here. I am not sure if this repo is a better place to post it:
https://github.com/mlverse/torch/issues/861

**Comment by dfalbel** [comment]
This is probably related to memory usage. torch v0.9.0 fixes a lot of those issues. Please retry and if the problem persists feel free to open a new issue.

**Comment by MislavSag** [comment]
I have installed the new version of torch but problem persists. The R studio crashes after executing fit part.

**Comment by dfalbel** [comment]
Can you try running from R in the terminal? This would allow us to at least have a traceback.

**Comment by MislavSag** [comment]
If I run the script from powershell I get an error: R for windows front-end stop has stopped working

**Comment by dfalbel** [comment]
What's your Cudnn version? You can query with:

```
torch::backends_cudnn_version()
```

My is that the crash is caused by a compatibility issue between CUDA and Cudnn.

**Comment by MislavSag** [comment]
> torch::backends_cudnn_version()
[1] ‘8.3.2’

**Comment by MislavSag** [comment]
I don't understand why it show version 8.3.2 when I have installed verison 8.4.0:
```
(base) PS C:\Users\Mislav> cat "C:/Program Files/NVIDIA GPU Computing Toolkit/CUDA/v11.3/include/cudnn_v*.h" | grep CUDNN_MAJOR -A2
#define CUDNN_MAJOR 8
#define CUDNN_MINOR 4
#define CUDNN_PATCHLEVEL 0
--
#define CUDNN_VERSION (CUDNN_MAJOR * 1000 + CUDNN_MINOR * 100 + CUDNN_PATCHLEVEL)

#endif /* CUDNN_VERSION_H */
```

**Comment by MislavSag** [comment]
It finally works after update to the new version of R (from 4.2.1 to 4.2.2). I have reinstalled all packages. Don't what what was the main issue, but it is working now.
