### ISSUE TITLE
Implement `find_lr`

### ISSUE THREAD

**Issue by dfalbel** [mlverse/luz#3]

**Comment by cmcmaster1** [comment]
Is anyone working on this?

**Comment by dfalbel** [comment]
I don't think there's anyone working on it yet

**Comment by cmcmaster1** [comment]
I have a basic lr finder (splits epoch up into desired number of steps, runs through one epoch with exponential lr increase at each step, logs lr and loss with optional plot). It's basically the lr finder from fastai v1 (no optimal lr algorithms or other bells and whistles).

**Comment by dfalbel** [comment]
That's awesome! Do you want to file a PR?

**Comment by cmcmaster1** [comment]
Will do.

**Comment by dfalbel** [comment]
Fixed in #59
