### ISSUE TITLE
Minimum and maximum number of epochs

### ISSUE THREAD

**Issue by mattwarkentin** [mlverse/luz#53]
Hi @dfalbel,

I'm wondering if you would consider allow the `epochs` argument to `fit.luz_module_generator()` to either accept a single integer (current behaviour) or a vector of two integers which represent the minimum and maximum number of epochs (e.g. `c(5, 10)`). 

Instead of just `ctx$epochs`, the context object could contain `ctx$min_epochs` and `ctx$max_epochs` which could be used by callbacks. If only a single number is provided it is `ctx$max_epochs` (and `ctx$min_epochs` would be set to 0 or 1?). A vector of two numbers would be `ctx$min_epochs <- epochs[[1]]` and `ctx$max_epochs <- epochs[[2]]`.

Then callbacks like `luz_callback_early_stopping()` could use `ctx$min_epochs` to avoid early stopping if the minimum number of epochs has not yet been achieved.

Thoughts??

**Comment by dfalbel** [comment]
I like this idea very much!

**Comment by mattwarkentin** [comment]
Cool! Will submit a PR soon.
