### ISSUE TITLE
Examples dont run on their own

### ISSUE THREAD

**Issue by GitHubGeniusOverlord** [mlverse/luz#86]
Hi,

I tried two of the examples for luz:
https://mlverse.github.io/luz/articles/examples/mnist-autoencoder.html
https://mlverse.github.io/luz/articles/examples/dogs-vs-casts-binary-classification.html

both fail at the start where they expect some data to lie on drive. 
Maybe it would be better to have the data come with the torchdataset-package.
I was a bit lost here concerning what to do exactly. 

From the Autoencoder-Example
`> 
#...........
train_ds <- mnist_dataset2(
+   dir,
+   download = TRUE,
+   transform = transform_to_tensor
+ )
Error in utils::download.file(r[1], destfile = destpath) : 
  cannot open destfile '~/Downloads/mnist/mnist/raw/train-images-idx3-ubyte.gz', reason 'No such file or directory'`

From the Classification-Example:
`#............
> ds <- torchdatasets::dogs_vs_cats_dataset(
+   dir,
+   token = "~/Downloads/kaggle.json",
+   download = TRUE,
+   transform = . %>%
+     torchvision::transform_to_tensor() %>%
+     torchvision::transform_resize(size = c(224, 224)) %>% 
+     torchvision::transform_normalize(rep(0.5, 3), rep(0.5, 3)),
+   target_transform = function(x) as.double(x) - 1
+ )
Error: Kaggle token file '~/Downloads/kaggle.json' does not exist.`

**Comment by dfalbel** [comment]
Should be better now as we are hosting both datasets. Needs dev version of torchdatasets for now.
